-- ============================================================
-- Krantos Platform — Initial Schema Migration
-- Requirements: 5.1, 5.2, 15.2
-- ============================================================

-- ============================================================
-- ENUM TYPES
-- ============================================================

CREATE TYPE subscription_type_enum AS ENUM ('free', 'basic', 'premium');
CREATE TYPE vendor_status_enum AS ENUM ('pending', 'active', 'suspended');
CREATE TYPE lead_status_enum AS ENUM ('new', 'contacted', 'converted', 'lost');
CREATE TYPE unit_enum AS ENUM ('W', 'A', 'V');

-- ============================================================
-- TABLE: users
-- Stores end-user information collected during power calculation
-- ============================================================

CREATE TABLE users (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name  varchar(100) NOT NULL,
    last_name   varchar(100) NOT NULL,
    phone       varchar(20)  NOT NULL,
    location    varchar(200) NOT NULL,
    created_at  timestamp    DEFAULT now()
);

-- ============================================================
-- TABLE: vendors
-- Stores vendor (business) accounts on the marketplace
-- ============================================================

CREATE TABLE vendors (
    id                uuid                   PRIMARY KEY DEFAULT gen_random_uuid(),
    name              varchar(200)           NOT NULL,
    category          varchar(100)           NOT NULL,
    phone             varchar(20)            NOT NULL,
    email             varchar(200)           UNIQUE,
    subscription_type subscription_type_enum NOT NULL DEFAULT 'free',
    status            vendor_status_enum     DEFAULT 'pending',
    created_at        timestamp              DEFAULT now()
);

-- ============================================================
-- TABLE: products
-- Stores energy products offered by vendors
-- ============================================================

CREATE TABLE products (
    id           uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    vendor_id    uuid         NOT NULL REFERENCES vendors(id) ON DELETE CASCADE,
    name         varchar(200) NOT NULL,
    category     varchar(100) NOT NULL,
    power_rating float        NOT NULL,
    price        decimal(12,2) NOT NULL,
    description  text,
    keywords     text,
    is_active    boolean      DEFAULT true,
    created_at   timestamp    DEFAULT now()
);

-- ============================================================
-- TABLE: leads
-- Stores qualified leads generated by power calculations
-- ============================================================

CREATE TABLE leads (
    id                     uuid             PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                uuid             REFERENCES users(id),
    user_name              varchar(200)     NOT NULL,
    user_phone             varchar(20)      NOT NULL,
    location               varchar(200)     NOT NULL,
    total_power_needed     float            NOT NULL,
    recommended_product_id uuid             REFERENCES products(id),
    vendor_id              uuid             REFERENCES vendors(id),
    status                 lead_status_enum DEFAULT 'new',
    created_at             timestamp        DEFAULT now()
);

-- ============================================================
-- TABLE: appliances_input
-- Stores individual appliances associated with a lead
-- ============================================================

CREATE TABLE appliances_input (
    id              uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id         uuid         NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    appliance_name  varchar(200) NOT NULL,
    quantity        integer      NOT NULL CHECK (quantity >= 1),
    power           float        NOT NULL,
    unit            unit_enum    NOT NULL,
    power_in_watts  float        NOT NULL
);

-- ============================================================
-- INDEXES
-- Optimise frequent queries (Requirement 15.2)
-- ============================================================

CREATE INDEX idx_products_power_rating ON products(power_rating);
CREATE INDEX idx_leads_vendor_id       ON leads(vendor_id);
CREATE INDEX idx_leads_status          ON leads(status);
